version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node
      - image: circleci/mongo:4.2.1
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
